Base/Base/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('recportal.urls')),
]

# anything in static should be considered public and hence this is exceptable
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Base/recportal/urls.py
from django.conf.urls import url
from recportal import views

app_name = 'recportal'
urlpatterns = [
    url(r'^signin/$', views.SignIn, name='signin'),
    url(r'^signout/$', views.SignOut, name='signout'),
    url(r'^$', views.Home, name='home'),
    url(r'^recommendations/$', views.Recommendations, name='recommendations'),
    url(r'^my-candidates/$', views.MyCandidates, name='mycandidates'),
    url(r'^candidates/$', views.Candidates, name='candidates'),
    url(r'^profile/(?P<first_name>[A-Za-z_]+)-(?P<last_name>[A-Za-z_]+)/$', views.CandidateProfile, name='profile'),
    url(r'^assess/(?P<first_name>[A-Za-z_]+)-(?P<last_name>[A-Za-z_]+)/$', views.AssessCandidate, name='assess'),
    url(r'^recommend/(?P<first_name>[A-Za-z_]+)-(?P<last_name>[A-Za-z_]+)/$', views.RecommendCandidate, name='recommend'),
    url(r'^my-assessments/$', views.MyAssessments, name="myassessments"),
    url(r'^assessments/$', views.Assessments, name="assessments"),
    url(r'^download/(?P<filename>.+)/$', views.Download, name="download"),
    url(r'^edit/(?P<first_name>[A-Za-z_]+)-(?P<last_name>[A-Za-z_]+)/$', views.EditCandidate, name='edit'),
    url(r'^updatepassword/$', views.UpdatePassword, name="updatepassword")
]

Base/recportal/views.py
import os
import re
from datetime import datetime

from django.conf import settings
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, redirect, get_object_or_404

from recportal.mimeTypes import MIME_TYPES
from recportal.models import *


@login_required
def Candidates(request):
    ''' the view to render the candidates page '''

    if request.method == 'GET':
        context = {}
        context['data'] = Candidate.objects.all()
        return render(request, 'recportal/candidates.html', context)

    if request.method == 'POST':
        # for when the candidate is being updated
        data = request.POST
        try:
            first_name = data['first_name'].replace(' ', '_')
            last_name = data['last_name'].replace(' ', '_')
            if not last_name:
                last_name = "IDK"
            ph = data["ph"]
            if not re.match(r'(^[0-9]{10}$)', ph):
                if not re.match(r'^91([0-9]{10})$', ph):
                	messages.add_message(request, messages.ERROR, 'Invalid phone number.')
                	return redirect('recportal:candidates')

            try:
                email = data["email"]
                if email == '':
                    raise KeyError
                if not re.match(r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)",email):
                    messages.add_message(request, messages.ERROR, 'Invalid email address.')
                    return redirect('recportal:candidates')
            except KeyError:
                pass

            try:
                skill1 = data['skill1']
            except:
                skill1 = ''
            try:
                skill2 = data['skill2']
            except:
                skill2 = ''
            try:
                about = data['about']
            except:
                about = ''

        except Exception as err:
            messages.add_message(request, messages.ERROR, 'Essential data missing.')
            return redirect('recportal:candidates')

        Candidate.objects.create(first_name=first_name, last_name=last_name, ph=ph, email=email, skill1=skill1, skill2=skill2, about=about ,pitched=False)
        messages.add_message(request, messages.INFO, 'Candidate successfully created!')
        return redirect('recportal:candidates')

    else:
        return JsonResponse({'error_message':'Invalid request method.'})


@login_required
def CandidateProfile(request, first_name, last_name):
    ''' the induvisual profile page for each candidate '''

    if request.method == 'GET':
        context = {}
        context['candidate'] = get_object_or_404(Candidate, first_name=first_name, last_name=last_name)
        return render(request, 'recportal/profile.html', context)

    else:
        return JsonResponse({'error_message':'Invalid request method.'})

@login_required
def Download(request, filename):
    try:
        filetype = filename.split(".")[-1]
    except IndexError: # default to text
        filetype = "txt"
    try:
        mimetype = MIME_TYPES[filetype]
    except KeyError:
        filetype = "txt"
        mimetype = "text/plain"
    with open(os.path.join(settings.MEDIA_ROOT, filename), "rb") as f:
        response = HttpResponse(f.read(), content_type=mimetype)
        response["Content-Disposition"] = "inline; filename=" + filename
    return response



@login_required
def EditCandidate(request, first_name, last_name):

    if request.method == "POST":
        candidate = get_object_or_404(Candidate, first_name=first_name, last_name=last_name)
        data = request.POST
        try:
            candidate.first_name = data['first_name'].replace(' ', '_')
            candidate.last_name = data['last_name'].replace(' ', '_')


            ph = data["ph"]
            if not re.match(r'(^[0-9]{10}$)', ph):
                if not re.match(r'^91([0-9]{10})$', ph):
                    messages.add_message(request, messages.ERROR, 'Invalid phone number.', extra_tags="edit")
                    return redirect('recportal:profile', first_name, last_name)
            else:
                candidate.ph = ph

            try:
                email = data["email"]
                if email == '':
                    raise KeyError
                if not re.match(r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)",email):
                    messages.add_message(request, messages.ERROR, 'Invalid email address.', extra_tags="edit")
                    return redirect('recportal:profile', first_name, last_name)
                else:
                    candidate.email = email
            except KeyError:
                candidate.email = ''

            try:
                candidate.skill1 = data['skill1']
            except:
                candidate.skill1 = ''
            try:
                candidate.skill2 = data['skill2']
            except:
                candidate.skill2 = ''
            try:
                candidate.about = data['about']
            except:
                candidate.about = ''

        except Exception as err:
            messages.add_message(request, messages.ERROR, 'Essential data missing.', extra_tags="edit")
            return redirect('recportal:profile', candidate.first_name, candidate.last_name)

        candidate.save()
        messages.add_message(request, messages.INFO, 'Candidate successfully edited!', extra_tags="edit")
        return redirect('recportal:profile', candidate.first_name, candidate.last_name)

    else:
        return JsonResponse({"message": "invalid request method."})

@login_required
def Home(request):
    ''' the first page you go to after logging in '''

    if request.method == 'GET':
        return render(request, 'recportal/home.html')

    else:
        return JsonResponse({'error_message':'Invalid request method.'})


@login_required
def MyCandidates(request):
    ''' the view to render the mycandidates page '''

    if request.method == 'GET':
        context = {}
        context['data'] = request.user.senior.getCandidates()
        return render(request, 'recportal/mycandidates.html', context)

    else:
        return JsonResponse({'error_message':'Invalid request method.'})


@login_required
def MyAssessments(request):

    if request.method == 'GET':
        context = {}
        context['myassessments'] = request.user.assessments.all()
        return render(request, 'recportal/myassessments.html', context)

    if request.method == 'POST':
        data = request.POST
        files = request.FILES
        candidate = get_object_or_404(Candidate, first_name=data['candidate'].split('-')[0], last_name=data['candidate'].split('-')[1])
        assessment = get_object_or_404(Assessment, candidate=candidate, senior=request.user)
        if data["doc"]:
            assessment.task.completion_date = datetime.datetime.strptime(data['doc'], '%Y-%m-%d').date()
        if "pitched" in data.keys():
            assessment.pitched = True
        if "rubric" in files.keys():
            assessment.task.rubric = files["rubric"]
        assessment.task.save()
        assessment.save()
        messages.add_message(request, messages.INFO, 'Task updated successfully!')
        return redirect('recportal:myassessments')

    else:
        return JsonResponse({'error_message':'Invalid request method.'})


@login_required
def AssessCandidate(request, first_name, last_name):
    ''' the view for the form to assess candidates '''

    if request.method == 'GET':
        context = {}
        context['candidate'] = get_object_or_404(Candidate, first_name=first_name, last_name=last_name)
        return render(request, 'recportal/assess.html', context)

    if request.method == 'POST':
        # don't forget to make a verification script
        data = request.POST
        files = request.FILES
        # first, don't let the same senior assess the same candidate more than once
        try:
            candidate= get_object_or_404(Candidate, first_name=first_name, last_name=last_name)
            p = Assessment.objects.get(candidate=candidate, senior=request.user)
            if p:
                messages.add_message(request, messages.ERROR, 'You have already assessed this candidate', extra_tags="assessment")
            return redirect('recportal:profile', first_name=first_name, last_name=last_name)
        except:
            pass
        # then, make sure that all of the data is valid and create the new assessment
        possible_teams = ['App Dev', 'Backend', 'Frontend', 'Graphics', 'Video']
        try:
            team = data['team']
            if team not in possible_teams:
                messages.add_message(request, messages.ERROR, 'Assessment cancelled due to providing an invalid team. Stay away from dev tools.', extra_tags="assessment")
                return redirect('recportal:profile', first_name=first_name, last_name=last_name)
            title = data['title']
            desc = data['description']

            isd = datetime.datetime.strptime(data['issuing_date'], '%Y-%m-%d').date()

            if "rubric" in files.keys():
                rubric = files["rubric"]
                # no extra security measures are taken to check the type of the file uploaded
                # since this webapp is closed only to member of a department, there is no need for it.
            else:
                rubric = None

            try:
                dd = datetime.datetime.strptime(data['due_date'], '%Y-%m-%d').date()
                task = Task.objects.create(title=title, description=desc, issuing_date=isd, due_date=dd, candidate=candidate, rubric=rubric)
            except:
                task = Task.objects.create(title=title, description=desc, issuing_date=isd, candidate=candidate, rubric=rubric)

Base/recportal/templates/recportal/assess.html
{% extends 'recportal/base.html' %}

{% block title %}
  <title> Recruitments Portal -- Assess </title>
  <style>
    .desc
      {
        height: 50px;
        width: 500px;
        resize: both;
        background-color: #f5f5f5;
      }
  </style>
{% endblock %}

{% block content %}
<br>
<div class="container">
  <form method="post" action="{% url 'recportal:assess' first_name=candidate.first_name last_name=candidate.last_name %}" id="assess" enctype="multipart/form-data">
    {% csrf_token %}
    <h3 class="center-align"> Assess {{candidate.first_name}} {{candidate.last_name}} </h3>
    <br>
    <table>
      <tr>
        <td class="teamtd"> <label for="team"> Team: </label> </td>
        <td>
            <div class="input-field">
              <select form="assess" name="team" class="browser-default grey lighten-4" required>
                <option value="App Dev">App Dev</option>
                <option value="Backend">Backend</option>
                <option value="Frontend">Frontend</option>
                <option value="Graphics">Graphics</option>
                <option value="Video">Video</option>
              </select>
            </div>
        </td>
        <!-- <td> <input type="text" name="team" maxlength="10" required /> </td> -->
      </tr>
    </table>

    <br><br><br>

    <h4 class="center-align"> Task Details </h4>

    <table>
      <tr>
        <td> <label for="title"> Title: </label> </td>
        <td> <input type="text" name="title" maxlength="50" required /> </td>
      </tr>
      <tr>
        <td> <label for="issuing_date"> Issuing Date: </label> </td>
        <td> <input type="date" name="issuing_date" required /> </td>
      </tr>
      <tr>
        <td> <label for="due_date"> Due Date: </label> </td>
        <td> <input type="date" name="due_date" /> </td>
      </tr>
      <tr>
        <td> <label for="description"> Description: </label> </td>
        <td> <textarea name="description" maxlength="100" class="desc" form="assess" required></textarea> </td>
      </tr>
      <tr>
        <td> <label for="rubric"> Rubric (optional): </label> </td>
        <td> <input type="file" name="rubric" /> </td>
      </tr>
    </table>

    <br><br>

    <div class="center-align">
      <input type="submit" value="Create Assessment" class="btn-large yellow lighten-1 grey-text">
    </div>

    <br>

  </form>
</div>
{% endblock %}

Base/recportal/templates/recportal/assessments.html
{% extends 'recportal/base.html' %}

{% block title %}
  <title> Recruitments Portal -- All Assessments </title>
{% endblock %}

{% block content %}
<div class="container" >
  <br>
  <table>

    <tr>
      <td colspan="4" class="center-align light-blue lighten-1"><b> Assessment Details </b></td>
      <td colspan="6" class="center-align light-blue lighten-2"><b> Task Details </b></td>
    </tr>

    <tr>
      <td class="light-blue lighten-1"><b> Candidate </b></td>
      <td class="light-blue lighten-1"><b> Senior </b></td>
      <td class="light-blue lighten-1"><b> Potential Team </b></td>
      <td class="light-blue lighten-1"><b> Pitched </b></td>
      <td class="light-blue lighten-2"><b> Title </b></td>
      <td class="light-blue lighten-2"><b> Description </b></td>
      <td class="light-blue lighten-2"><b> Issuing Date </b></td>
      <td class="light-blue lighten-2"><b> Due Date </b></td>
      <td class="light-blue lighten-2"><b> Date of Completion </b></td>
      <td class="light-blue lighten-2"><b> Rubric </b></td>


    </tr>

    {% for assessment in assessments %}
    <tr class="light-blue lighten-4">
      <td> <a href="{% url 'recportal:profile' assessment.candidate.first_name assessment.candidate.last_name %}"> {{assessment.candidate.first_name}} {{assessment.candidate.last_name}} </a> </td>
      <td> {{assessment.senior.first_name}} {{assessment.senior.last_name}} </td>
      <td> {{assessment.team}} </td>
      <td> {{assessment.pitched}} </td>
      <td> {{assessment.task.title}} </td>
      <td> {{assessment.task.description}} </td>
      <td> {{assessment.task.issuing_date}} </td>
      <td> {{assessment.task.due_date}} </td>

            {% if assessment.task.completion_date %}
              <td class="green-text">
                {{assessment.task.completion_date}} {% if assessment.task.is_overdue %}<br><p class="red-text"> (overdue) </p>{% endif %}
             </td>
            {% elif assessment.task.is_overdue %}
              <td class="red-text"> overdue </td>
            {% elif assessment.task.is_ongoing %}
              <td> ongoing </td>
            {% else %}
              <td> error, please notify the dev </td>
            {% endif %}

      <td> {% if assessment.task.rubric %} <a href="{% url 'recportal:download' filename=assessment.task.rubric.name %}"> {{assessment.task.rubric.name}} </a> {% else %} None {% endif %} </td>

    </tr>
    {% endfor %}
  </table>
</div>

<br>

{% endblock %}

Base/recportal/templates/recportal/base.html
<!DOCTYPE html>

<html>

<head>
  {% block title %}{% endblock %}
  {% load static %}
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="shortcut icon" href="{%  static 'recportal/favicon.ico' %}">
  <link type="text/css" rel="stylesheet" href="{% static 'recportal/css/materialize.min.css' %}"  media="screen,projection"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body class="grey lighten-3">

  <div id="body-wrapper">

     <nav class="blue darken-4">
       <div class="nav-wrapper">
         <a href="{% url 'recportal:home' %}" class="brand-logo">RecPortal</a>
         <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
           <ul class="right hide-on-med-and-down">
          <li><a href="{% url 'recportal:assessments' %}">All Assessments</a></li>
          <li><a href="{% url 'recportal:candidates' %}">All Candidates</a></li>
      <li><a class="dropdown-trigger"  data-target="dropdown2">Senior Panel<i class="material-icons right">arrow_drop_down</i></a></li>

          <ul id='dropdown2' class='dropdown-content'>
            <li><a href="{% url 'recportal:myassessments' %}">My Assessments</a></li>
            <li><a href="{% url 'recportal:mycandidates' %}">My Candidates</a></li>
            <li>
          <a href="{% url 'recportal:recommendations' %}">Recommendations
            <span class="badge">{{request.user.senior.active_recommendations_count}}</span>
          </a>
        </li>
          </ul>
          <li><a href="{% url 'recportal:signout' %}">Signout</a></li>
           </ul>
      </div>
      </nav>

      <ul class="sidenav" id="mobile-demo">
      <li><a href="{% url 'recportal:assessments' %}">All Assessments</a></li>
      <li><a href="{% url 'recportal:candidates' %}">All Candidates</a></li>
      <li><a class="dropdown-trigger"  data-target="dropdown1">Senior Panel<i class="material-icons right">arrow_drop_down</i></a></li>
      <li><a href="{% url 'recportal:signout' %}">Signout</a></li>

          <ul id='dropdown1' class='dropdown-content'>
            <li><a href="{% url 'recportal:myassessments' %}">My Assessments</a></li>
            <li><a href="{% url 'recportal:mycandidates' %}">My Candidates</a></li>
            <li>
          <a href="{% url 'recportal:recommendations' %}">Recommendations
            <span class="badge">{{request.user.senior.active_recommendations_count}}</span>
          </a>
        </li>
          </ul>
     </ul>

  </div>

  {% block content %}
  {% endblock %}

  <!--JavaScript at end of body for optimized loading-->
  <script type="text/javascript" src="{% static 'recportal/js/jquery-3.3.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'recportal/js/materialize.min.js' %}"></script>


  <script>
  $('document').ready(function() {
    $(".sidenav").sidenav()
    $(".dropdown-trigger").dropdown();
    $(".modal").modal({
      //dismissible: false,
    });
  })
  </script>
</body>

</html>

Base/recportal/templates/recportal/home.html
{% extends 'recportal/base.html' %}

{% block title %}
  <title> Recruitments Portal -- Home Page </title>
{% endblock %}

{% block content %}
  <h2> Welcome {{request.user.get_full_name.title}}. </h2>
  <br>
  <p> You can change your password <a href="{% url 'recportal:updatepassword' %}"> here </a> at anytime if you'd like.</p>
{% endblock %}

Base/recportal/templates/recportal/profile.html
{% extends 'recportal/base.html' %}

{% block title %}
  <title> Recruitments Portal -- {{candidate.first_name}} {{candidate.last_name}} </title>
  <style>
    .no_border
    {
      margin: 0!important;;
      padding: 0!important;
      border: 0!important;
      box-shadow: none!important;
    }
    .padded
    {
      padding-right: 100px !important;
      padding-left: 100px !important;
    }
  </style>
  <script>
    function editView() {
        document.getElementById("name").innerHTML = "<b><i> First Name: </i></b><input type=\"text\" name=\"first_name\" form=\"edit_form\" value=\"{{candidate.first_name}}\" /><b><i> Last Name: </i></b><input type=\"text\" name=\"last_name\" form=\"edit_form\" value=\"{{candidate.last_name}}\" />";
        document.getElementById("about").innerHTML = "<b> About: </b> <textarea id=\"about_textar\" name=\"about\" form=\"edit_form\" />";
        document.getElementById("about_textar").defaultValue = "{{candidate.about}}";
        document.getElementById("skill1").innerHTML = "<b> Skill 1: </b> <input type=\"text\" name=\"skill1\" form=\"edit_form\" value=\"{{candidate.skill1}}\" />";
        document.getElementById("skill2").innerHTML = "<b> Skill 2: </b> <input type=\"text\" name=\"skill2\" form=\"edit_form\" value=\"{{candidate.skill2}}\" />";
        document.getElementById("ph").innerHTML = "<b> Phone Number: </b> <input type=\"number\" name=\"ph\" form=\"edit_form\" value=\"{{candidate.ph}}\" />";
        document.getElementById("email").innerHTML = "<b> Email Address: </b> <input type=\"email\" name=\"email\" form=\"edit_form\" value=\"{{candidate.email}}\" />";
        document.getElementById("edit_button").innerHTML = "<input type=\"submit\" class=\"btn-large green\" form=\"edit_form\" value=\"update\" /><br><p>(refresh page to cancel)</p>";
    }
  </script>
{% endblock %}

{% block content %}

  <br>
  <div name="info" class="container">
    <form method="post" action="{% url 'recportal:edit' candidate.first_name candidate.last_name %}" id="edit_form">
      {% csrf_token %}
    <table>

      <tr>
        <td class="center-align teal lighten-3" colspan="2" id="name"><h4><b><i>{{candidate.first_name}} {{candidate.last_name}}</i></b></h4></td>
      </tr>

      <tr>
        <td rowspan="2" width="50%" class="center-align teal lighten-5" id="about"><b> About: </b><br>{{candidate.about}}</td>
        <td class="center-align teal lighten-5" id="skill1"><b> Skill 1:</b>   {{candidate.skill1}}</td>
      </tr>

      <tr>
        <td class="center-align teal lighten-5" id="skill2"><b> Skill 2:</b>   {{candidate.skill2}}</td>
      </tr>

      <tr>
        <td class="center-align teal lighten-5" id="ph"><b> Phone Number: </b>  {{candidate.ph}} </td>
        <td class="center-align teal lighten-5" id="email"><b> Email Address: </b>  {{candidate.email}} </td>
      </tr>

    </form>
    </table>
  </div>

  <br>

  <div name="action" class="container">
    <table>
      <tr class="no_border">
        <td class="center-align"><a href="{% url 'recportal:assess' first_name=candidate.first_name last_name=candidate.last_name %}" class="btn-large hoverable"> Assess </a></td>
        <td class="center-align"><a href="{% url 'recportal:recommend' first_name=candidate.first_name last_name=candidate.last_name %}" class="btn-large hoverable"> Recommend </a></td>
        <td class="center-align" id="edit_button"><a onclick="editView()" class="btn-large hoverable"> Edit </a></td>
        {% if messages %}
          {% for message in messages %}
            <div class="center-align">
            {% if forloop.counter == 1 %}
              {% if message.tags == 'edit error' %}
                <p class="red-text"><i> {{ message }} </i></p>
              {% elif message.tags == 'edit info' %}
                <p class="green-text"><i> {{ message }} </i></p>
              {% endif %}
            {% endif %}
            </div>
          {% endfor %}
        {% endif %}
      </tr>
      {% if messages %}
        <tr class="no_border">
              <td>
            {% for message in messages %}{% if forloop.counter == 1 %}
              <div class="center-align">
                {% if message.tags == 'assessment error' %}
                  <p class="red-text"><i> {{ message }} </i></p>
                {% elif message.tags == 'assessment info' %}
                  <p class="green-text"><i> {{ message }} </i></p>
                {% endif %}
              </div>
            {% endif %}{% endfor %}
            </td>

            <td>
          {% for message in messages %}{% if forloop.counter == 1 %}
            <div class="center-align">
              {% if message.tags == 'recommend error' %}
                <p class="red-text"><i> {{ message }} </i></p>
              {% elif message.tags == 'recommend info' %}
                <p class="green-text"><i> {{ message }} </i></p>
              {% endif %}
            </div>
          {% endif %}{% endfor %}
          </td>

        </tr>
      {% endif %}
    </table>
  </div>

  <br>
  <br>

  <div name="assessments" class="padded">
    <h5> Existing Assessments: </h5>
    <table>
      <tr>
        <td> Team </td>
        <td> Task </td>
        <td> Senior </td>
        <td> Pitched </td>
      </tr>

      {% for assessment in candidate.assessments.all %}
      <tr>
        <td> {{assessment.team}} </td>
        <td> {% if assessment.task %} (ID={{assessment.task.id}}) {% endif %} {{assessment.task}} </td>
        <td> {{assessment.senior}} </td>
        <td> {{assessment.pitched}} </td>
      </tr>
      {% endfor %}
    </table>
  </div>

  <br><br>

  <div name="tasks" class="padded">
    <h5> Assigned Tasks: </h5>
    <table>
      <tr>
        <td> Title </td>
        <td> Issuing Date </td>
        <td> Due Date </td>
        <td> Completion Date </td>
        <td> Description </td>
        <td> Rubric </td>
      </tr>

      {% for assessment in candidate.assessments.all %}
      {% if assessment.task %}
      <tr>
        <td>  (ID={{assessment.task.id}}) {{assessment.task}} </td>
        <td> {{ assessment.task.issuing_date }} </td>
        <td> {{ assessment.task.due_date }}</td>
        <td> {{ assessment.task.completion_date }}</td>
        <td> {{assessment.task.description}} {% if not assessment.task.due_date %} (casual) {% endif %} </td>
        <td> {% if assessment.task.rubric %} <a href="{% url 'recportal:download' filename=assessment.task.rubric.name %}"> {{assessment.task.rubric.name}} </a> {% else %} None {% endif %} </td>
      </tr>
      {% endif %}
      {% endfor %}
    </table>
  </div>

{% endblock %}

Base/recportal/templates/recportal/recommend.html
{% extends 'recportal/base.html' %}

{% block title %}
  <title> Recruitments Portal -- Recommend </title>
  <style>
  .txtar
    {
      height: 50px;
      width: 500px;
      resize: both;
      background-color: #f5f5f5;
    }
  </style>
  <script>
    function visInduvisual(){
      document.getElementById("mode=team").style.visibility = "hidden";
      document.getElementById("mode=induvisual").style.visibility = "visible";
    }
    function visTeam(){
      document.getElementById("mode=induvisual").style.visibility = "hidden";
      document.getElementById("mode=team").style.visibility = "visible";
    }
  </script>
{% endblock %}

{% block content %}

  <br>
    <h3 class="center-align"> Recommend {{candidate.first_name}} {{candidate.last_name}} </h3>
  <br>


  <div class="container">
  <form action="{% url 'recportal:recommend' first_name=candidate.first_name last_name=candidate.last_name %}" method="post" id="recommend">
    {% csrf_token %}
    <table>

      <tr>
        <td class="right-align"><label> <input type="radio" name="mode" value="induvisual" class="browser-default" onclick="visInduvisual()" required/><span> induvisual </span></label></td>
        <td class="center-align"><label>  <input type="radio" name="mode" value="team" class="browser-default" onclick="visTeam()" required/><span> team </span></label></td>
      </tr>

      <tr id="mode=induvisual" style="visibility:hidden">
        <td> To: </td>
        <td>
          <select form="recommend" name="senior" class="browser-default" required>
            {% for senior in all_seniors %}{% if senior != request.user %}
              <option value="{{senior.first_name}}-{{senior.last_name}}">  {{senior.first_name}} {{senior.last_name}} </option>
            {% endif %}{% endfor %}
          </select>
        </td>
      </tr>

      <tr id="mode=team" style="visibility:hidden">
        <td> To: </td>
        <td>
          <select form="recommend" name="team" class="browser-default" required>
              <option value="App Dev"> App Dev </option>
              <option value="Backend"> Backend </option>
              <option value="Frontend"> Frontend </option>
              <option value="Graphics"> Graphics </option>
              <option value="Video"> Video </option>
          </select>
        </td>
      </tr>

      <tr>
        <td> Reason: </td>
        <td> <textarea form="recommend" name="reason" class="txtar"></textarea> </td>
      </tr>

    </table>

    <br>

    <div class="center-align">
      <input type="submit" value="recommend!" class="btn-large yellow lighten-1 grey-text">
    </div>

    <br>

  </form>
{% endblock %}